### ISSUE TITLE
After some time, the Sensorlogger web interface cannot be reached due to missing base table or view (Exception thrown in error log)

### ISSUE THREAD

**Issue by e-alfred** [alexstocker/sensorlogger#54]
## Expected Behavior
Sensorlogger webinterface should open up normally inside Nextcloud.

## Actual Behavior
After some time, an exception is thrown if the Sensorlogger app is opened. A database restart fixes the problem for some time until it starts to reappear. An error message is shown and the following can be found in the log:

```
{"reqId":"W5y24H8AAQEAAAX7bpwAAAAL","level":3,"time":"2018-09-15T09:38:09+02:00","remoteAddr":"1.1.1.1","user":"user","app":"index","method":"GET","url":"\/owncloud\/apps\/sensorlogger\/","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT `id`, `device_uuid`, `humidity`, `temperature`, `data`, `created_at` FROM `oc_sensorlogger_logs` WHERE (device_uuid = \\\"6e1c74ec-c3b7-11e7-b5de-3f29aabb03f0\\\") AND (user_id = \\\"alfred\\\") ORDER BY `id` DESC LIMIT 10 OFFSET 0':\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_sensorlogger_logs' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `d...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(195): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `d...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `d...', Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(214): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/sensorlogger\\\/lib\\\/SensorLogs.php(96): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/sensorlogger\\\/lib\\\/Widgets.php(71): OCA\\\\SensorLogger\\\\SensorLogs::getLogsByUuId('alfred', '6e1c74ec-c3b7-1...', Object(OC\\\\DB\\\\Connection), 10)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/sensorlogger\\\/controller\\\/sensorloggercontroller.php(354): OCA\\\\SensorLogger\\\\Widgets::build('alfred', Object(OCA\\\\SensorLogger\\\\Device), Object(stdClass), Object(OC\\\\DB\\\\Connection), Object(OC\\\\AllConfig))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/sensorlogger\\\/controller\\\/sensorloggercontroller.php(140): OCA\\\\SensorLogger\\\\Controller\\\\SensorLoggerController->getWidgets()\\n#9 [internal function]: OCA\\\\SensorLogger\\\\Controller\\\\SensorLoggerController->index()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\SensorLogger\\\\Controller\\\\SensorLoggerController), 'index')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\SensorLogger\\\\Controller\\\\SensorLoggerController), 'index')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\SensorLogge...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/apps\\\/sensorlog...')\\n#17 \\\/var\\\/www\\\/owncloud\\\/index.php(42): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"13.0.6.1"}
```

I have two devices sending temperature and humidity to Sensorlogger using the Python script.

## Steps to Reproduce the Problem

  1. Run Sensorlogger for some time.

## Specifications

  - Version: 0.0.7
  - Platform: Nextcloud 13.0.6

**Comment by e-alfred** [comment]
I found that the oc_sensorlogger_logs.ibd table is 670 MB in size. Could this be a problem?

**Comment by alexstocker** [comment]
I would guess, this peoblem could be environment var related. Im running SensorLogger within owncloud for a while now with db size far beyound 2GB. So, sorry I do not have a clue. 
You may check your HD too.

**Comment by e-alfred** [comment]
I dumped the database and removed the Mysql folder. Then I restored it and now it works. It seems to be that the specific table I mentioned above got corrupt somehow.

Thanks for your help.
